[mysql]
host = "127.0.0.1"
port = ":3306"
dbname = "zj"
username = "root"
password = "admin123"
maxIdleConns = 10
maxOpenConns = 100

[http]
port = ":8050"
debug = true

[static]
port = ":8083"
dir = "./web/"